spring:
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  h2:
    console:
      enable: true
      path: /h2-console
server:
  port: 8080
  servlet:
    contextPath: /
springdoc:
  show-actuator: true
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  .api-docs:
    enabled: true